### PR TITLE
Do not free waker until safe

### LINKED ISSUE #84: Racy test failure: segfault in map::tree_bins::concurrent_tree_bin
This is [this issue](https://github.com/jonhoo/flurry/issues/83#issuecomment-612070827) which I've factored out into its own issue. Basically, the `map::tree_bins::concurrent_tree_bin` test occasionally segfaults for me without a backtrace. I can reproduce on current nightly on Linux by running this command for a while:
```console
$ while cargo test --lib map::tree_bins::concurrent_tree_bin -- --test-threads=1 --nocapture; do :; done
```
Using `gdb`, I managed to capture a stack trace:
```
Thread 21 "flurry-27205002" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5632700 (LWP 349291)]
std::thread::Thread::unpark () at src/libstd/thread/mod.rs:1191
1191    src/libstd/thread/mod.rs: No such file or directory.
(gdb) bt
#0  std::thread::Thread::unpark () at src/libstd/thread/mod.rs:1191
#1  0x00005555555eadb2 in flurry::node::TreeBin<K,V>::find (bin=..., hash=0, key=0x7ffff56317f8, guard=0x7ffff56317b8) at src/node.rs:472
#2  0x00005555555e3594 in flurry::raw::Table<K,V>::find (self=0x5555557839d0, bin=0x555555784f70, hash=0, key=0x7ffff56317f8, guard=0x7ffff56317b8) at src/raw/mod.rs:174
#3  0x00005555555bc56c in flurry::map::HashMap<K,V,S>::get_node (self=0x555555780b40, key=0x7ffff56317f8, guard=0x7ffff56317b8) at src/map.rs:1314
#4  0x00005555555bcd1e in flurry::map::HashMap<K,V,S>::get (self=0x555555780b40, key=0x7ffff56317f8, guard=0x7ffff56317b8) at src/map.rs:1387
#5  0x000055555559540e in flurry::map::tree_bins::concurrent_tree_bin::{{closure}} () at src/map.rs:3406
#6  0x00005555555abe91 in std::sys_common::backtrace::__rust_begin_short_backtrace (f=...) at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys_common/backtrace.rs:130
#7  0x000055555558f4a1 in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} () at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:475
#8  0x00005555555d6db1 in <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (self=..., _args=()) at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318
#9  0x00005555555a353a in std::panicking::try::do_call (data=0x7ffff5631998 "0\vxUUU\000") at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:331
#10 0x00005555555a370d in __rust_try ()
#11 0x00005555555a3393 in std::panicking::try (f=...) at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:274
#12 0x00005555555d6e31 in std::panic::catch_unwind (f=...) at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394
#13 0x000055555558ec19 in std::thread::Builder::spawn_unchecked::{{closure}} () at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:474
#14 0x00005555555875ae in core::ops::function::FnOnce::call_once{{vtable-shim}} () at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
#15 0x00005555556cf61f in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once () at /rustc/94d346360da50f159e0dc777dc9bc3c5b6b51a00/src/liballoc/boxed.rs:1008
#16 0x00005555556e25b3 in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once () at /rustc/94d346360da50f159e0dc777dc9bc3c5b6b51a00/src/liballoc/boxed.rs:1008
#17 std::sys::unix::thread::Thread::new::thread_start () at src/libstd/sys/unix/thread.rs:87
#18 0x00007ffff7f7746f in start_thread () from /usr/lib/libpthread.so.0
#19 0x00007ffff7e8d3d3 in clone () from /usr/lib/libc.so.6
```

### PR DESCRIPTION
**Pull request by jonhoo**
It is possible for someone to try to wake a waiting thread while that
thread is spinning. In that case, the waiting thread may decide to free
its waker just before the waking thread tries to wake the waiting one,
resulting in a use-after-free.

This fixes that by deferring the freeing of the waker until the next
epoch.

Seems to fix #84.

---
This change is [Reviewable](https://reviewable.io/reviews/jonhoo/flurry/85)

### CODE REVIEW

**Comment by jonhoo** [comment]
Seems I spoke too soon. Just got this panic:
```
thread '<unnamed>' panicked at 'inconsistent state in unpark', src/libstd/thread/mod.rs:1195:18
stack backtrace:
...
  11: std::panicking::begin_panic
             at src/libstd/panicking.rs:438
  12: std::thread::Thread::unpark
             at src/libstd/thread/mod.rs:1195
  13: flurry::node::TreeBin<K,V>::find
             at src/node.rs:472
  14: flurry::raw::Table<K,V>::find
             at src/raw/mod.rs:174
  15: flurry::map::HashMap<K,V,S>::get_node
             at src/map.rs:1314
  16: flurry::map::HashMap<K,V,S>::get
             at src/map.rs:1387
  17: flurry::map::tree_bins::concurrent_tree_bin::{{closure}}
             at src/map.rs:3405
```

**Comment by jonhoo** [comment]
It looks like this _may_ also fix #83 somehow. At least I haven't been able to reproduce it with this fix. I'll keep running it for a bit.

**Comment by jonhoo** [comment]
Nope, finally got another crash similar to #83, so this probably _just_ fixes #84. It _does_ seem to fix that though, so I'll merge :tada:

File: src/node.rs [hunk 1]
```diff
@@ -371,7 +371,11 @@ impl<K, V> TreeBin<K, V> {
                         // not obtain new references to our thread handle. Also,
                         // we just swapped out that handle, so it is no longer
                         // reachable.
-                        let _ = unsafe { waiter.into_owned() };
+                        //
+                        // Now, we cannot safely drop this _immediately_, since
+                        // we may have woken up and reached here _while_ some
```
Comment (domenicquirl) [inline src/node.rs:376]: Sorry for only getting to reviewing this after you already merged, but I think you're missing something like a "reading thread" or "one" here 😅

Comment (domenicquirl) [reply src/node.rs:376]: Also I think once we actually park, we cannot get here before the call to unpark (so it would be only if we _intended_ to wait, but then saw that the reader was gone in the re-check before, in a context switch from after the reader saw the `WAITER` in `lock_state`). But I think the general case is clear enough.

Comment (jonhoo) [reply src/node.rs:376]: Good catch! Fixed in cd19e2cc88b6c10aed77b795c77f365678a3c441
